#pragma once
// OceanEterna v8.0 — mmap-based inverted index
// Eliminates in-memory hash maps: server RAM drops from ~89GB to ~5GB at 50B scale
//
// Three index files (generated by bulk_build):
//   stems.idx      — pre-merged stem -> posting lists (replaces inverted_index + g_stem_to_keywords + g_stem_cache)
//   doc_keywords.idx — per-document keyword IDs (replaces DocMeta.keyword_ids for Phase 2 coverage)
//   keywords.idx   — keyword_id -> stem_id mapping (for Phase 2 coverage scoring)

#include <string>
#include <cstdint>
#include <cstring>
#include <cmath>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <algorithm>
#include <iostream>
#include <vector>

// FNV-1a 64-bit hash (must match builder)
static inline uint64_t fnv1a_64(const char* data, size_t len) {
    uint64_t hash = 0xcbf29ce484222325ULL;
    for (size_t i = 0; i < len; i++) {
        hash ^= (uint8_t)data[i];
        hash *= 0x100000001b3ULL;
    }
    return hash;
}

struct MmapFile {
    void* data = nullptr;
    size_t size = 0;
    int fd = -1;

    bool open(const std::string& path) {
        fd = ::open(path.c_str(), O_RDONLY);
        if (fd < 0) return false;
        struct stat st;
        fstat(fd, &st);
        size = st.st_size;
        data = mmap(nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0);
        if (data == MAP_FAILED) { ::close(fd); data = nullptr; return false; }
        return true;
    }

    void close() {
        if (data && data != MAP_FAILED) munmap(data, size);
        if (fd >= 0) ::close(fd);
        data = nullptr; fd = -1; size = 0;
    }

    const uint8_t* ptr() const { return (const uint8_t*)data; }

    template<typename T> T read_at(size_t offset) const {
        T val; memcpy(&val, ptr() + offset, sizeof(T)); return val;
    }
};

struct MmapIndex {
    MmapFile stems_file;    // stems.idx
    MmapFile doc_kw_file;   // doc_keywords.idx
    MmapFile kw_stem_file;  // keywords.idx

    // parsed from stems.idx header
    uint64_t stem_count = 0;
    uint64_t postings_start = 0;
    double avg_dl = 0;
    const uint8_t* stem_dir = nullptr;     // pointer to stem directory
    const uint8_t* stem_strings = nullptr; // pointer to stem strings section
    const uint8_t* postings = nullptr;     // pointer to postings section

    // parsed from doc_keywords.idx header
    uint64_t doc_count = 0;
    const uint8_t* doc_kw_dir = nullptr;
    const uint8_t* doc_kw_data = nullptr;
    size_t doc_kw_data_start = 0;

    // parsed from keywords.idx header
    uint64_t keyword_count = 0;
    const uint32_t* kw_to_stem = nullptr;

    bool loaded = false;

    bool load(const std::string& corpus_dir) {
        std::string stems_path = corpus_dir + "/stems.idx";
        std::string doc_kw_path = corpus_dir + "/doc_keywords.idx";
        std::string kw_stem_path = corpus_dir + "/keywords.idx";

        if (!stems_file.open(stems_path)) {
            std::cerr << "Failed to open " << stems_path << std::endl;
            return false;
        }
        if (!doc_kw_file.open(doc_kw_path)) {
            std::cerr << "Failed to open " << doc_kw_path << std::endl;
            return false;
        }
        if (!kw_stem_file.open(kw_stem_path)) {
            std::cerr << "Failed to open " << kw_stem_path << std::endl;
            return false;
        }

        // parse stems.idx header
        auto sp = stems_file.ptr();
        if (memcmp(sp, "OES1", 4) != 0) { std::cerr << "Bad stems.idx magic" << std::endl; return false; }
        stem_count = stems_file.read_at<uint64_t>(8);
        postings_start = stems_file.read_at<uint64_t>(16);
        uint64_t avg_dl_bits = stems_file.read_at<uint64_t>(24);
        memcpy(&avg_dl, &avg_dl_bits, 8);

        stem_dir = sp + 32; // directory starts right after header
        // stem strings start after directory (stem_count * 28 bytes per entry)
        stem_strings = stem_dir + stem_count * 28;
        postings = sp + postings_start;

        // parse doc_keywords.idx header
        auto dp = doc_kw_file.ptr();
        if (memcmp(dp, "OED1", 4) != 0) { std::cerr << "Bad doc_keywords.idx magic" << std::endl; return false; }
        doc_count = doc_kw_file.read_at<uint64_t>(8);
        doc_kw_dir = dp + 16;
        doc_kw_data_start = 16 + doc_count * 8;
        doc_kw_data = dp + doc_kw_data_start;

        // parse keywords.idx header
        auto kp = kw_stem_file.ptr();
        if (memcmp(kp, "OEK1", 4) != 0) { std::cerr << "Bad keywords.idx magic" << std::endl; return false; }
        keyword_count = kw_stem_file.read_at<uint64_t>(8);
        kw_to_stem = (const uint32_t*)(kp + 16);

        // madvise: pre-fault the directories (small, frequently accessed)
        madvise((void*)stem_dir, stem_count * 28, MADV_WILLNEED);
        madvise((void*)doc_kw_dir, doc_count * 8, MADV_WILLNEED);

        loaded = true;
        std::cout << "  mmap index loaded: " << stem_count << " stems, "
                  << doc_count << " docs, " << keyword_count << " keywords" << std::endl;
        return true;
    }

    void close() {
        stems_file.close();
        doc_kw_file.close();
        kw_stem_file.close();
        loaded = false;
    }

    // Stem directory entry layout (28 bytes):
    // [0:8] hash, [8:12] str_offset, [12:14] str_len, [14:18] posting_offset, [18:22] posting_count, [22:26] df, [26:28] padding

    struct StemEntry {
        uint64_t hash;
        uint32_t str_offset;
        uint16_t str_len;
        uint32_t posting_offset;
        uint32_t posting_count;
        uint32_t df;
    };

    StemEntry read_stem_entry(uint64_t idx) const {
        const uint8_t* p = stem_dir + idx * 28;
        StemEntry e;
        memcpy(&e.hash, p, 8);
        memcpy(&e.str_offset, p + 8, 4);
        memcpy(&e.str_len, p + 12, 2);
        memcpy(&e.posting_offset, p + 14, 4);
        memcpy(&e.posting_count, p + 18, 4);
        memcpy(&e.df, p + 22, 4);
        return e;
    }

    // binary search for a stem. returns posting list pointer + count + df, or {nullptr, 0, 0}
    struct LookupResult {
        const uint32_t* postings;
        uint32_t count;
        uint32_t df;
    };

    LookupResult lookup_stem(const std::string& stem) const {
        if (stem_count == 0) return {nullptr, 0, 0};

        uint64_t target_hash = fnv1a_64(stem.data(), stem.size());

        // binary search by hash
        uint64_t lo = 0, hi = stem_count;
        while (lo < hi) {
            uint64_t mid = lo + (hi - lo) / 2;
            auto entry = read_stem_entry(mid);

            if (entry.hash < target_hash) {
                lo = mid + 1;
            } else if (entry.hash > target_hash) {
                hi = mid;
            } else {
                // hash match - verify string
                const char* s = (const char*)(stem_strings + entry.str_offset);
                if (entry.str_len == stem.size() && memcmp(s, stem.data(), stem.size()) == 0) {
                    // found
                    const uint32_t* post = (const uint32_t*)(postings + entry.posting_offset);
                    return {post, entry.posting_count, entry.df};
                }
                // hash collision - scan both directions
                for (uint64_t i = mid; i > 0; ) {
                    i--;
                    auto e2 = read_stem_entry(i);
                    if (e2.hash != target_hash) break;
                    const char* s2 = (const char*)(stem_strings + e2.str_offset);
                    if (e2.str_len == stem.size() && memcmp(s2, stem.data(), stem.size()) == 0) {
                        return {(const uint32_t*)(postings + e2.posting_offset), e2.posting_count, e2.df};
                    }
                }
                for (uint64_t i = mid + 1; i < stem_count; i++) {
                    auto e2 = read_stem_entry(i);
                    if (e2.hash != target_hash) break;
                    const char* s2 = (const char*)(stem_strings + e2.str_offset);
                    if (e2.str_len == stem.size() && memcmp(s2, stem.data(), stem.size()) == 0) {
                        return {(const uint32_t*)(postings + e2.posting_offset), e2.posting_count, e2.df};
                    }
                }
                return {nullptr, 0, 0}; // hash collision but string didn't match
            }
        }
        return {nullptr, 0, 0};
    }

    // get keyword IDs for a document (Phase 2 rescoring)
    struct DocKeywords {
        const uint32_t* ids;
        uint16_t count;
    };

    DocKeywords get_doc_keywords(uint32_t doc_idx) const {
        if (doc_idx >= doc_count) return {nullptr, 0};
        const uint8_t* entry = doc_kw_dir + doc_idx * 8;
        uint32_t offset;
        uint16_t count;
        memcpy(&offset, entry, 4);
        memcpy(&count, entry + 4, 2);
        const uint32_t* ids = (const uint32_t*)(doc_kw_data + offset);
        return {ids, count};
    }

    // get stem_id for a keyword_id
    uint32_t get_keyword_stem(uint32_t keyword_id) const {
        if (keyword_id >= keyword_count) return UINT32_MAX;
        return kw_to_stem[keyword_id];
    }
};
